admindash/urls.py
from django.urls import path
from . import views

app_name="admindash"

urlpatterns = [
    path('admin_login/',views.admin_login, name='admin_login'),
    path('admin_home/',views.admin_home, name='admin_home'),
    path('list_user/',views.list_user,name='list_user'),
    path('user_block/<int:user_id>/', views.user_block, name='user_block'),
    path('user_unblock/<int:user_id>/', views.user_unblock, name='user_unblock'),
    path('order_status/<int:pk>/', views.order_status, name='order_status'),
    path('reports/',views.sales_report,name='sales_report'),
    path('filter/',views.order_date_filter,name='date_filter'),
    path('best_selling_products/',views.best_selling_products,name='best_selling_products'),
    path('best_selling_categories/',views.best_selling_categories,name='best_selling_categories'),
    path('best_selling_brands/',views.best_selling_brands,name='best_selling_brands'),
    path('logout/',views.logout,name='admin_logout'),
] 

brand/urls.py
from django.urls import path
from .views import *

app_name = 'brand'

urlpatterns = [
    path('brand', list_brand, name='list_brand'),
    path('create', create_brand, name='create_brand'),
    path('edit/<int:pk>/', EditBrand.as_view(), name='edit_brand'),
    path('delete/<int:pk>/', DeleteBrandView.as_view(), name='delete_brand'),
]

cart/urls.py
from django.urls import path
from . views import *
from . import views


app_name = 'cart'

urlpatterns = [
    path('add_to_cart',views.add_to_cart, name='add_to_cart'),
    path('list_cart/',views.list_cart, name='list_cart'),
    path('update_is_active/', views.update_is_active, name='update_is_active'),
    path('update-quantity/',views.update_cart_quantity, name='update_cart_quantity'),
    path('cart_checkout/',views.cart_checkout, name='cart_checkout'),
    path('remove_item_cart/<int:pk>/',views.remove_item_cart, name='remove_item_cart'),
    # path('apply-coupon/',views.apply_coupon, name='apply_coupon'),
    # path('remove-coupon/',views.remove_coupon, name='remove_coupon'),
]

coupon/urls.py
from django.urls import path
from . views import *
from . import views

app_name = 'coupon'

urlpatterns = [
    path('create_coupon/',views.create_coupon,name='create_coupon'),
     path('coupon/',views.coupon_list, name='coupon'),
     path('edit_coupon/<int:pk>/',views.edit_coupon, name='edit_coupon'),
     path('coupon_status/<int:pk>/',views.toggle_coupon_status, name='coupon_status')
]

dripdeck_backup/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
    path('admindash/',include('admindash.urls')),
    path('category/',include('category.urls')),
    path('brand/',include('brand.urls')),
    path('product/',include('product.urls')),
    path('userdash/',include('userdash.urls')),
    path('cart/',include('cart.urls')),
    path('order/',include('order.urls')),
    path('coupon/',include('coupon.urls')),
    path('auth/', include('social_django.urls', namespace='social')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path 
from . import views


app_name = 'order'

urlpatterns = [
    path('place_order/',views.orderverification, name='place_order'),
    path('order_success/',views.order_success, name='order_success'),
    path('list_order_admin/',views.list_order_admin, name='list_order_admin'),
    path('admin_orders_details/<int:pk>/',views.admin_orders_details, name='admin_orders_details'),
    path('cancel_order/<int:pk>/',views.cancel_order, name='cancel_order'),
    path('return_order/<int:pk>/',views.return_order, name='return_order'),
    path('razorpay-payment/', views.razorpay_payment, name='razorpay_payment'),
    path('razorpay-handler/', views.handle_razorpay_payment, name='handle_razorpay_payment'),
    path('applycoupon/', views.applycoupon, name='applycoupon'),
    path('return_requests/',views.admin_return_requests, name='return_requests'),
    path('admin_return_approval/<int:pk>/',views.admin_return_approval, name='admin_return_approval'),
    path('admin_cancel_order/<int:pk>/',views.admin_cancel_order, name='admin_cancel_order'),
    path('individual_cancel/<int:pk>/',views.individual_cancel, name='individual_cancel'),
    path('individual_return/<int:pk>/',views.individual_return, name='individual_return'),
    path('removecoupon/', views.removecoupon, name='removecoupon'),
  
]

product/urls.py
from django.urls import path

from .import views
from .views import CreateProductView, ListProduct, ProductDetailView

app_name = 'product'

urlpatterns = [
    path('list/', ListProduct.as_view(), name='list_product'),
    path('detail/<int:product_id>/', ProductDetailView.as_view(), name='product-detail'),
    path('create/', CreateProductView.as_view(), name='create_product'),
    path('edit/<int:product_id>',views.edit_product,name='edit-product'),
    path('status/<int:product_id>',views.product_status,name='product-status'),
    path('add-images/<int:product_id>',views.add_images,name='add-images'),
    path('add-variant/<int:product_id>',views.add_variant,name='add-variant'),
    path('variant/<int:product_id>/', views.variant_detail, name='variant-detail'),
    path('edit-variant/<int:variant_id>/',views.edit_variant, name='edit-variant'),
    path('variant-status/<int:variant_id>/',views.variant_status, name='variant-status'),
    path('product_images/<int:pk>/',views.product_images, name='product_images'),
    path('remove_images/<int:pk>/',views.remove, name='remove_images'),
    path('shop-page',views.shop_page, name='shop-page'),
    path('product-details/<int:pk>/', views.product_details, name='product-detailsuser'),
    path('review/<int:pk>',views.review, name='review'),
]

admindash/models.py
from django.db import models

# Create your models here.

admindash/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login
from accounts.models import User 
from order.models import *
from utils.decorators import admin_required
from django.db.models.functions import ExtractMonth, ExtractYear, TruncMonth
import json
from django.db.models import Sum, Count, F, Q
from datetime import timedelta
from django.utils import timezone
from datetime import datetime
from django.utils.timezone import now, timedelta
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout




def admin_login(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        
        user = authenticate(request, email=email, password=password)

        if user is not None:
            if user.is_admin:
                login(request, user)
                return redirect('admindash:admin_home')
            else:
                messages.error(request, 'You are not authorized to access this page.')
        else:
            messages.error(request, 'Invalid email or password.')

    return render(request, 'admindash/admin_login.html')


@admin_required
def admin_home(request):
    # Total order amount
        total_order_amount = OrderMain.objects.filter(order_status="delivered").aggregate(total=Sum('total_amount'))['total'] or 0
        
        # Total order count
        total_order_count = OrderMain.objects.filter(order_status="delivered").aggregate(total_orders=Count('id'))['total_orders'] or 0
        
        # Total discount
        total_discount = OrderMain.objects.filter(order_status="delivered").aggregate(
            total_discount=Sum(F('discount_amount'))
        )['total_discount'] or 0
        
        # Monthly earnings
        now = timezone.now()
        current_year = now.year
        current_month = now.month
        
        monthly_earnings = OrderMain.objects.filter(
            order_status="delivered",
            date__year=current_year,
            date__month=current_month
        ).aggregate(monthly_total=Sum('total_amount'))['monthly_total'] or 0

        # Data for the order chart
        monthly_order_count = OrderMain.objects.filter(
            order_status="delivered"
        ).annotate(
            month=ExtractMonth('date'),
            year=ExtractYear('date')
        ).values('year', 'month').annotate(count=Count('id')).order_by('year', 'month')

        labels = [f'{entry["month"]}/{entry["year"]}' for entry in monthly_order_count]
        data = [entry['count'] for entry in monthly_order_count]

        # User registration data
        user_registrations = User.objects.annotate(
            month=TruncMonth('date_joined')
        ).values('month').annotate(count=Count('id')).order_by('month')

        user_labels = [entry['month'].strftime('%b %Y') for entry in user_registrations]
        user_data = [entry['count'] for entry in user_registrations]

        context = {
            'total_order_amount': total_order_amount,
            'total_order_count': total_order_count,
            'total_discount': total_discount,
            'monthly_earnings': monthly_earnings,
            'labels': json.dumps(labels),
            'data': json.dumps(data),
            'user_labels': json.dumps(user_labels),
            'user_data': json.dumps(user_data)
        }
        
        return render(request,'admindash/admin_dash.html',context)


def sales_report(request):
    filter_type = request.GET.get('filter', None)
    now = timezone.now()
    start_date = end_date = None  # Initialize to None

    if filter_type == 'weekly':
        start_date = now - timedelta(days=now.weekday())
        end_date = now
    elif filter_type == 'monthly':
        start_date = now.replace(day=1)
        end_date = now

    # Filter orders based on whether a date range is defined
    if start_date and end_date:
        orders = OrderMain.objects.filter(
            order_status="delivered",
            is_active=True,
            date__range=[start_date, end_date]
        )
    else:
        # No specific filter, show all "Order Placed" orders
        orders = OrderMain.objects.filter(
            order_status="delivered",
            is_active=True
        )

    total_discount = orders.aggregate(total=Sum('discount_amount'))['total']
    total_orders = orders.aggregate(total=Count('id'))['total']
    total_order_amount = orders.aggregate(Sum('total_amount'))['total_amount__sum'] or 0

    return render(request, 'admindash/sales_report.html', {
        'orders': orders,
        'total_discount': total_discount,
        'total_orders': total_orders,
        'total_order_amount': total_order_amount
    })

def order_date_filter(request):
    if request.method == 'POST':
        start_date = request.POST.get('start_date')
        end_date = request.POST.get('end_date')
        
        if start_date and end_date:
            try:
                start_date = datetime.strptime(start_date, '%Y-%m-%d').date()
                end_date = datetime.strptime(end_date, '%Y-%m-%d').date()
            except ValueError:
                return redirect('admin_panel:sales_report')

            orders = OrderMain.objects.filter(
                date__range=[start_date, end_date], 
                order_status="Order Placed"
            )
            total_discount = orders.aggregate(total=Sum('discount_amount'))['total']
            total_orders = orders.aggregate(total=Count('id'))['total']
            total_order_amount = orders.aggregate(Sum('total_amount'))['total_amount__sum'] or 0

            return render(request, 'admindash/sales_report.html', {
                'orders': orders,
                'total_discount': total_discount,
                'total_orders': total_orders,
                'total_order_amount': total_order_amount
            })

    return redirect('admindash:sales_report')
    

@admin_required
def list_user(request):
    users = User.objects.filter(is_admin=False)
    return render(request, 'admindash/list_user.html', {'users': users})
@admin_required
def user_block(request, user_id):
    user = get_object_or_404(User, id=user_id)
    user.is_blocked = True
    user.save()
    messages.success(request, 'User blocked successfully.')
    return redirect('admindash:list_user')


@admin_required
def user_unblock(request, user_id):
    user = get_object_or_404(User, id=user_id)
    user.is_blocked = False
    user.save()
    messages.success(request, 'User unblocked successfully.')
    return redirect('admindash:list_user')

def order_status(request,pk):
    if request.method == 'POST':
        fk = pk
        order = get_object_or_404(OrderMain, id=pk)
        new_status = request.POST.get('order_status')
        
    if new_status:
        order.order_status = new_status
        order.save()
            
        return redirect('order:admin_orders_details',fk)
    else:
        return HttpResponse("No status selected", status=400)




def best_selling_products(request):
    best_selling_products = OrderSub.objects.filter(
        main_order__order_status="delivered"
    ).values(
        'variant__product__id',
        'variant__product__product_name'
    ).annotate(
        total_sold=Sum('quantity')
    ).order_by('-total_sold')
    
    top_product = best_selling_products.first()

    return render(request, 'admindash/best_selling_product.html', {
        'top_product': top_product,
        'best_selling_products': best_selling_products
    })


def best_selling_categories(request):
    best_selling_categories = OrderSub.objects.filter(
        main_order__order_status="delivered"
    ).values(
        'variant__product__product_category__id',
        'variant__product__product_category__category_name',
        'variant__product__thumbnail'  # Include the thumbnail
    ).annotate(
        total_sold=Sum('quantity')
    ).order_by('-total_sold')
    
    top_category = best_selling_categories.first()

    return render(request, 'admindash/best_selling_category.html', {
        'top_category': top_category,
        'best_selling_categories': best_selling_categories
    })


def best_selling_brands(request):
    best_selling_brands = OrderSub.objects.filter(
        main_order__order_status="delivered"
    ).values(
        'variant__product__product_brand__id',
        'variant__product__product_brand__brand_name',
        'variant__product__product_brand__brand_image'  # Include brand image
    ).annotate(
        total_sold=Sum('quantity')
    ).order_by('-total_sold')

    top_brand = best_selling_brands.first()

    return render(request, 'admindash/best_selling_brand.html', {
        'top_brand': top_brand,
        'best_selling_brands': best_selling_brands
    })


def logout(request):
    auth_logout(request)
    return redirect('admindash:admin_login') 

templates/admindash/base_admin.html
{% load static %}
<!DOCTYPE HTML>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Admin Dashboard</title>
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta property="og:title" content="">
    <meta property="og:type" content="">
    <meta property="og:url" content="">
    <meta property="og:image" content="">
    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static  'assets/images/drip/favicsde.ico' %}">
    <!-- Template CSS -->
    <link href="{% static 'admindash/assets/css/main.css' %}" rel="stylesheet" type="text/css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.6/cropper.css" rel="stylesheet"/>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/css/bootstrap.min.css" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.6/cropper.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/js/bootstrap.bundle.min.js"></script>
</head>

<body>
    <div class="screen-overlay"></div>
    <aside class="navbar-aside" id="offcanvas_aside">
        <div class="aside-top">
            <a href="index.html" class="brand-wrap">
                <img src="{% static 'assets/images/drip/mainlogodrip.svg' %}" class="logo" alt="Evara Dashboard">
            </a>
            <div>
                <button class="btn btn-icon btn-aside-minimize"> <i class="text-muted material-icons md-menu_open"></i> </button>
            </div>
        </div>
        <nav>
            <ul class="menu-aside">
                <li class="menu-item ">
                    <a class="menu-link" href="{% url 'admindash:admin_home' %}"> <i class="icon material-icons md-home"></i>
                        <span class="text">Dashboard</span>
                    </a>
                </li>
                <li class="menu-item ">
                    <a class="menu-link" href="{% url 'admindash:list_user' %}"> <i class="icon material-icons md-person"></i>
                        <span class="text">User Management</span>
                    </a>
                    
                </li>
                <li class="menu-item ">
                    <a class="menu-link" href="{% url 'category:list-category' %}"> <i class="icon material-icons md-shopping_bag"></i>
                        <span class="text">Category</span>
                    </a>
                   
                </li>
                <li class="menu-item ">
                    <a class="menu-link" href="{% url 'product:list_product' %}"> <i class="icon material-icons md-add_box"></i>
                        <span class="text">product Management</span>
                    </a>
                </li>
                <li class="menu-item ">
                    <a class="menu-link" href="{% url 'brand:list_brand' %}"> <i class="icon material-icons md-stars"></i>
                        <span class="text">Brands</span>
                    </a>
                    
                </li>
                <li class="menu-item ">
                    <a class="menu-link" href="{% url 'order:list_order_admin' %}"> <i class="icon material-icons md-shopping_cart"></i>
                        <span class="text">Orders</span>
                    </a>
                    
                </li>
                <li class="menu-item ">
                    <a class="menu-link" href="{% url 'coupon:coupon' %}"> <i class="icon material-icons md-monetization_on"></i>
                        <span class="text">Coupon</span>
                    </a>
                    
                </li>
                <li class="menu-item">
                    <a class="menu-link" href="{% url 'order:return_requests' %}"><i class="icon material-icons md-replay"></i>
                        <span class="text">Returns</span>
                    </a>
                    
                </li>
               
            </ul>
            <hr>
            <ul class="menu-aside">
               
            </ul>
            <br>
            <br>
        </nav>
    </aside>
    <main class="main-wrap">
        <header class="main-header navbar">
            <div class="col-search">
                <form class="searchform">
                    <div class="input-group">
                        <input list="search_terms" type="text" class="form-control" placeholder="Search term">
                        <button class="btn btn-light bg" type="button"> <i class="material-icons md-search"></i></button>
                    </div>
                    <datalist id="search_terms">
                        <option value="Products">
                        <option value="New orders">
                        <option value="Apple iphone">
                        <option value="Ahmed Hassan">
                    </datalist>
                </form>
            </div>
            <div class="col-nav">
                
                <ul class="nav">
                    <li class="nav-item">
                        <a class="nav-link btn-icon" href="#">
                        
                         
                        </a>
                    </li>
                    
                    </li>
                    <li class="dropdown nav-item">
                        <a class="dropdown-toggle" data-bs-toggle="dropdown" href="#" id="dropdownAccount" aria-expanded="false"> <img class="img-xs rounded-circle" src="{% static 'assets/images/drip/admins.jpg' %}" alt="User"></a>
                        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownAccount">
                            
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item text-danger" href="{% url 'admindash:admin_logout' %}"><i class="material-icons md-exit_to_app"></i>Logout</a>
                        </div>
                    </li>
                </ul>
            </div>
        </header>
{% block content %}
{% endblock %}

templates/admindash/list_user.html
{% extends 'admindash/base_admin.html' %}
{% load static %}
{% block content %}

<section class="content-main">
    <div class="content-header">
        <div>
            <h2 class="content-title card-title">User management</h2>
        </div>
        <div>
            <input type="text" placeholder="Search order ID" class="form-control bg-white">
        </div>
    </div>
    <div class="card mb-4">
        <header class="card-header">
            <div class="row gx-3">
                <div class="col-lg-4 col-md-6 me-auto">
                    <input type="text" placeholder="Search..." class="form-control">
                </div>
            </div>
        </header> <!-- card-header end// -->
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th scope="col">Email</th>
                            <th scope="col">First Name</th>
                            <th scope="col">Last Name</th>
                            <th scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for user in users %}
                        <tr>
                            <td>{{ user.id }}</td>
                            <td>{{ user.first_name }}</td>
                            <td>{{ user.last_name }}</td>
                            <td>{{ user.email }}</td>                         
                            
                            <td>
                                {% if user.is_blocked %}
                                <a href="#" class="btn btn-success btn-sm" onclick="confirmAction('{% url 'admindash:user_unblock' user.id %}', 'Are you sure you want to unblock this user?')">Unblock</a>
                                {% else %}
                                <a href="#" class="btn btn-warning btn-sm" onclick="confirmAction('{% url 'admindash:user_block' user.id %}', 'Are you sure you want to block this user?')">Block</a>
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div> <!-- table-responsive//end -->
        </div>
    </div>
</section>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script> <!-- Ensure SweetAlert2 is included -->
<script>
    function confirmAction(url, message) {
        Swal.fire({
            title: 'Are you sure?',
            text: message,
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, do it!'
        }).then((result) => {
            if (result.isConfirmed) {
                window.location.href = url;
            }
        });
    }
</script>

{% endblock content %}

templates/admindash/product_detail.html
{% extends 'admindash/base_admin.html' %}
{% load static %}
{% block title %} 
<title>Product Detail</title>
{% endblock title %}
{% block content %}
<section class="content-main">
    <div class="content-header">
        <div class="d-flex justify-content-between align-items-center mb-4">
            <h2 class="content-title card-title mb-0">Product Detail</h2>
        </div>
    </div>

    <div class="card mb-4">
        <div class="row g-0">
            <div class="col-md-1">
                <div class="thumbnail-list">
                    {% comment %} {% for image in images %}
                    <img src="{{ image.images.url }}" class="img-fluid img-thumbnail thumbnail-image" alt="Product Image" onclick="swapImage(this)">
                    {% endfor %} {% endcomment %}
                </div>
            </div>
            <div class="col-md-4">
                <div class="main-thumbnail mb-3">
                    {% if products.thumbnail %}
                    <img id="main-thumbnail" src="{{ products.thumbnail.url }}" class="img-fluid rounded main-image" alt="{{ products.product_name }}">
                    {% else %}
                    <img id="main-thumbnail" src="{% static 'placeholder_image.jpg' %}" class="img-fluid rounded main-image" alt="Placeholder Image">
                    {% endif %}
                </div>
            </div>
            <div class="col-md-6">
                <div class="card-body">
                    <h5 class="card-title">{{ products.product_name }}</h5>
                    <table class="table">
                        <tbody>
                            <tr>
                                <th scope="row">Category</th>
                                <td>{% if products.product_category %}{{ products.product_category.category_name }}{% else %}No category{% endif %}</td>
                            </tr>
                            <tr>
                                <th scope="row">Brand</th>
                                <td>{% if products.product_brand %}{{ products.product_brand.brand_name }}{% else %}No brand{% endif %}</td>
                            </tr>
                            <tr>
                                <th scope="row">Price</th>
                                <td>{{ products.price }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Offer Price</th>
                                <td>{{ products.offer_price }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Discount</th>
                                <td>{{ products.percentage_discount }}%</td>
                            </tr>
                            <tr>
                                <th scope="row">Status</th>
                                <td>
                                    <span class="badge rounded-pill {% if products.is_active %}bg-success{% else %}bg-danger{% endif %}">
                                        {{ products.is_active|yesno:"Active,Inactive" }}
                                    </span>
                                </td>
                            </tr>
                            <tr>
                                <th scope="row">Description</th>
                                <td>{{ products.product_description }}</td>
                            </tr>
                        </tbody>
                    </table>
                    <div class="btn-group mt-3" role="group">
                        <form method="post" action="{% url 'product:product-status' products.id %}" id="statusForm{{ products.id }}">
                            {% csrf_token %}
                            <button type="button" class="btn {% if products.is_active %}btn-danger{% else %}btn-success{% endif %} me-2 status-button" data-product-id="{{ products.id }}">Status</button>
                        </form>
                        <a href="{% url 'product:edit-product' products.id %}" class="btn btn-warning me-2">Edit</a>
                        {% comment %} <a href="{% url 'product:add-images' products.id %}" class="btn btn-info me-2">Add Images</a> {% endcomment %}
                        <a href="{% url 'product:variant-detail' products.id %}" class="btn btn-secondary me-2">Variant</a>
                        
                        <a href="{% url 'product:product_images' products.id %}" class="btn btn-secondary me-2">Add image</a>
                        
                        <a href="{% url 'product:list_product' %}" class="btn btn-secondary me-2">Back</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>
<h5>products Images</h5>
        <div class="d-flex flex-wrap">
            {% for image in images %}
                <div class="card me-2 mb-2" style="width: 18rem;">
                    <div class="card-body">
                        <img src="{{ image.images.url }}" class="img-thumbnail" alt="products Image">
                        <a href="{% url 'product:remove_images' image.id %}" class="btn btn-danger me-2">Remove</a> 
                    </div>
                </div>
            {% endfor %}
        </div>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
<script>
    function swapImage(thumbnail) {
        var mainThumbnail = document.getElementById('main-thumbnail');
        var mainThumbnailSrc = mainThumbnail.src;
        mainThumbnail.src = thumbnail.src;
        thumbnail.src = mainThumbnailSrc;
    }

    function confirmStatusChange(productId) {
        Swal.fire({
            title: 'Are you sure?',
            text: 'You are about to change the status.',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, do it!'
        }).then((result) => {
            if (result.isConfirmed) {
                document.getElementById('statusForm' + productId).submit();
            }
        });
    }

    document.querySelectorAll('.status-button').forEach(item => {
        item.addEventListener('click', event => {
            event.preventDefault();
            const productId = item.getAttribute('data-product-id');
            confirmStatusChange(productId);
        });
    });
</script>

<style>
    .main-image {
        max-width: 100%;
        max-height: 500px;
        object-fit: contain;
    }
    .thumbnail-image {
        width: 100px;
        height: 100px;
        object-fit: cover;
        cursor: pointer;
        margin-bottom: 10px;
    }
</style>

{% endblock content %}