accounts/urls.py
from django.urls import path 
from . import views

app_name = 'accounts'

urlpatterns = [
    path('',views.home,name='home'),
    path('login/',views.login,name='login'),
    path('signup/',views.signup,name='signup'),
    path('user/',views.user,name='user'),
    path('verify_otp/', views.verify_otp, name='verify_otp'),
    path('resend_otp',views.resend_otp,name='resend_otp'),
    path('logout',views.logout,name='logout'),
    path('verify_otp/', views.verify_otp, name='verify_otp'),
    path('about_us/', views.about_us, name='about_us'),
    path('contact_us/', views.contact_us, name='contact_us'),
    path('password-reset/',views.password_reset_request, name='password_reset'),
    path('password-reset-done/', views.password_reset_done, name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.password_reset_confirm, name='password_reset_confirm'),
    path('reset/done/', views.password_reset_complete, name='password_reset_complete'),
]

admindash/urls.py
from django.urls import path
from . import views

app_name="admindash"

urlpatterns = [
    path('admin_login/',views.admin_login, name='admin_login'),
    path('admin_home/',views.admin_home, name='admin_home'),
    path('list_user/',views.list_user,name='list_user'),
    path('user_block/<int:user_id>/', views.user_block, name='user_block'),
    path('user_unblock/<int:user_id>/', views.user_unblock, name='user_unblock'),
    path('order_status/<int:pk>/', views.order_status, name='order_status'),
    path('reports/',views.sales_report,name='sales_report'),
    path('filter/',views.order_date_filter,name='date_filter'),
    path('best_selling_products/',views.best_selling_products,name='best_selling_products'),
    path('best_selling_categories/',views.best_selling_categories,name='best_selling_categories'),
    path('best_selling_brands/',views.best_selling_brands,name='best_selling_brands'),
    path('logout/',views.logout,name='admin_logout'),
] 

cart/urls.py
from django.urls import path
from . views import *
from . import views


app_name = 'cart'

urlpatterns = [
    path('add_to_cart',views.add_to_cart, name='add_to_cart'),
    path('list_cart/',views.list_cart, name='list_cart'),
    path('update_is_active/', views.update_is_active, name='update_is_active'),
    path('update-quantity/',views.update_cart_quantity, name='update_cart_quantity'),
    path('cart_checkout/',views.cart_checkout, name='cart_checkout'),
    path('remove_item_cart/<int:pk>/',views.remove_item_cart, name='remove_item_cart'),
    # path('apply-coupon/',views.apply_coupon, name='apply_coupon'),
    # path('remove-coupon/',views.remove_coupon, name='remove_coupon'),
]

dripdeck_backup/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
    path('admindash/',include('admindash.urls')),
    path('category/',include('category.urls')),
    path('brand/',include('brand.urls')),
    path('product/',include('product.urls')),
    path('userdash/',include('userdash.urls')),
    path('cart/',include('cart.urls')),
    path('order/',include('order.urls')),
    path('coupon/',include('coupon.urls')),
    path('auth/', include('social_django.urls', namespace='social')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path 
from . import views


app_name = 'order'

urlpatterns = [
    path('place_order/',views.orderverification, name='place_order'),
    path('order_success/',views.order_success, name='order_success'),
    path('list_order_admin/',views.list_order_admin, name='list_order_admin'),
    path('admin_orders_details/<int:pk>/',views.admin_orders_details, name='admin_orders_details'),
    path('cancel_order/<int:pk>/',views.cancel_order, name='cancel_order'),
    path('return_order/<int:pk>/',views.return_order, name='return_order'),
    path('razorpay-payment/', views.razorpay_payment, name='razorpay_payment'),
    path('razorpay-handler/', views.handle_razorpay_payment, name='handle_razorpay_payment'),
    path('applycoupon/', views.applycoupon, name='applycoupon'),
    path('return_requests/',views.admin_return_requests, name='return_requests'),
    path('admin_return_approval/<int:pk>/',views.admin_return_approval, name='admin_return_approval'),
    path('admin_cancel_order/<int:pk>/',views.admin_cancel_order, name='admin_cancel_order'),
    path('individual_cancel/<int:pk>/',views.individual_cancel, name='individual_cancel'),
    path('individual_return/<int:pk>/',views.individual_return, name='individual_return'),
    path('removecoupon/', views.removecoupon, name='removecoupon'),
  
]

userdash/urls.py
from django.urls import path
from . import views


app_name = 'userdash'

urlpatterns = [
    path('user-profile/',views.user_profile,name='user-profile'), 
    path('add-address/',views.add_address,name='add-address'),
    path('changepass/',views.changepass,name='changepass'),
    path('edituser/',views.edituser,name='edituser'),
    path('default/<int:pk>/',views.default,name='default'),
    path('delete/<int:pk>/',views.delete,name='delete'),
    path('toggle-address-status/',views.toggle_address_status , name='toggle_address_status'),
    path('add-addresstwo/',views.add_addresstwo,name='add-addresstwo'),
    path('edit_address/<int:pk>/',views.edit_address,name='edit_address'),
    path('search/', views.search, name='search'),
    path('add-to-wishlist/',views.add_to_wishlist,name='add_to_wishlist'),
    path('wishlist/',views.wishlist,name='wishlist'),
    path('remove_wishlist/<int:pk>/',views.remove_wishlist,name='remove_wishlist'),
    path('wishlist-add-to-cart/', views.wishlist_add_to_cart, name='wishlist_add_to_cart'),
    path('user_invoice/<int:pk>/', views.user_invoice,name='user_invoice'),

]

order/views.py
from decimal import Decimal
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.crypto import get_random_string
from cart.models import *
from userdash.models import *
from datetime import datetime, timedelta
from .models import *
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from coupon.models import*
import razorpay
from django.http import JsonResponse
import json
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from utils.decorators import admin_required
# Create your views here.

def orderverification(request):
    current_user = request.user
    cart = Cart.objects.get(user=current_user)
    cart_items = CartItem.objects.filter(cart=cart, is_active=True)
    address = UserAddress.objects.filter(user=current_user,is_deleted=False,order_status=True).first()
    cart_total = sum(item.sub_total() for item in cart_items)

    coupon_code = request.session.get('applied_coupon', None)
    discount_amount = 0
    final_amount = cart_total
    if coupon_code:
        try:
            coupon = Coupon.objects.get(coupon_code=coupon_code)
            if cart_total >= coupon.minimum_amount:
                discount = coupon.discount
                discount_amount = (cart_total * discount / 100)
                discount_amount = min(discount_amount, coupon.maximum_amount)
                
                final_amount = cart_total - discount_amount
            else:
                messages.error(request, f'Coupon only available for orders over {coupon.minimum_amount}')
        except Coupon.DoesNotExist:
            pass

    payment_option = request.POST.get('payment_option')
    print(payment_option)
    
    if payment_option is None:
        messages.error(request, 'Select Payment Option')
        return redirect('cart:cart_checkout')
        
    if not address:
        messages.error(request, 'Select Address To Continue')
        return redirect('cart:cart_checkout')

    for cart_item in cart_items:
        if not cart_item.variant.variant_status:
             messages.error(request,'variant is unavailable')
             return redirect('cart:cart_checkout')


        if cart_item.variant.variant_stock < 1:
            messages.error(request, 'Out of stock')
            return redirect('cart:cart_checkout')
        
        if not cart_item.product.is_active:
                messages.error(request, 'Product unavailable')
                return redirect('cart:cart_checkout') 
        

    if payment_option =="Razorpay":

        return redirect('order:razorpay_payment')
    
    if payment_option =="Wallet":
        user = request.user
        try:
            wallet = Wallet.objects.get(user=user)
            wallet_amount = wallet.balance

            cart_items = CartItem.objects.filter(cart__user=request.user, is_active=True)
            new_total = sum(item.sub_total() for item in cart_items)

            if new_total <= wallet_amount:
                wallet = Wallet.objects.get(user=current_user)
                address = UserAddress.objects.get(user=current_user, order_status=True)
                payment_option = "Wallet Payment"
                
                current_date_time = datetime.now()
                formatted_date_time = current_date_time.strftime("%H%m%S%Y")
                unique = get_random_string(length=4, allowed_chars='1234567890')
                user = str(request.user.id)
                order_id = user + formatted_date_time + unique
                
                formatted_date_time = current_date_time.strftime("%m%Y%H%S")
                unique = get_random_string(length=2, allowed_chars='1234567890')
                payment_id = unique + user + formatted_date_time

                coupon_code = request.session.get('applied_coupon', None)
                discount = 0
                final_amount = new_total
                discount_amount = 0
                
                if coupon_code:
                    try:
                        coupon = Coupon.objects.get(coupon_code=coupon_code)
                        discount = coupon.maximum_amount
                        discount_amount = (new_total * discount / 100)
                        if discount_amount > discount:
                            discount_amount = discount
                        final_amount -= discount_amount

                    except Coupon.DoesNotExist:
                        pass
                            
                order_address = OrderAddress.objects.create(
                    name=address.name,
                    house_name=address.house_name,
                    street_name=address.street_name,
                    pin_number=address.pin_number,
                    district=address.district,
                    state=address.state,
                    country=address.country,
                    phone_number=address.phone_number
                )
                
                order_status = "Confirmed"
                
                order_main = OrderMain.objects.create(
                    user=current_user,
                    address=order_address,
                    total_amount=new_total,
                    final_amount=final_amount,
                    discount_amount=discount_amount,
                    payment_option=payment_option,
                    order_id=order_id,
                    order_status=order_status,
                    payment_id=payment_id,
                    payment_status=True
                )

                for cart_item in cart_items:
                    OrderSub.objects.create(
                        user=current_user,
                        main_order=order_main,
                        variant=cart_item.variant,
                        price=cart_item.product.offer_price,
                        quantity=cart_item.quantity,
                    )

                    cart_item.variant.variant_stock -= cart_item.quantity
                    cart_item.variant.save()
                    
                order_amount = new_total
                description = "Product Purchased With Wallet"
                transaction_type = "Debited"
                
                transaction = Transaction.objects.create(
                    wallet=wallet,
                    description=description,
                    amount=order_amount,
                    transaction_type=transaction_type,
                )

                wallet.balance -= final_amount 
                wallet.save()
                
                cart_items.delete()

                if coupon_code:
                    try:
                        coupon = Coupon.objects.get(coupon_code=coupon_code)
                        used_coupon = UserCoupon.objects.create(
                            user = request.user,
                            coupon = coupon,
                            used = True,
                            order = order_main
                        )

                    except Coupon.DoesNotExist:
                        pass
                
                request.session['order_id'] = order_main.order_id
                request.session['order_date'] = order_main.date.strftime("%Y-%m-%d")
                request.session['order_status'] = order_main.order_status
                
                request.session.pop('applied_coupon', None)
                
                messages.success(request, 'Order Success')
                
                return redirect('order:order_success')
            else:
                messages.error(request, 'Not Enough Money In Wallet')
                return redirect('cart:cart_checkout')
        except Wallet.DoesNotExist:
            messages.error(request, 'Wallet Does Not Exist')
            return redirect('cart:cart_checkout')
        except Exception as e:
            messages.error(request, str(e))
            return redirect('cart:cart_checkout')
    


    if payment_option == "Cash On Delivery":
        cart_items = CartItem.objects.filter(cart__user=request.user, is_active=True)
        new_total = sum(item.sub_total() for item in cart_items)
          
        if cart_total <= 6000: 
            user = str(request.user.id)
            current_date_time = datetime.now()
            formatted_date_time = current_date_time.strftime("%H%m%S%Y")
            unique = get_random_string(length=4, allowed_chars='1234567890')
            order_id = user + formatted_date_time + unique
            
            formatted_date_time = current_date_time.strftime("%m%Y%H%S")
            unique = get_random_string(length=2, allowed_chars='1234567890')
            payment_id = unique + user + formatted_date_time

            coupon_code = request.session.get('applied_coupon', None)
            discount = 0
            final_amount = new_total
            discount_amount = 0
            
            if coupon_code:
                try:
                    coupon = Coupon.objects.get(coupon_code=coupon_code)
                    discount = coupon.maximum_amount
                    discount_amount = (new_total * discount / 100)
                    if discount_amount > discount:
                        discount_amount = discount
                    final_amount -= discount_amount

                except Coupon.DoesNotExist:
                    pass

            order_address = OrderAddress.objects.create(
                name = address.name,
                house_name = address.house_name,
                street_name = address.street_name,
                pin_number = address.pin_number,
                district = address.district,
                state = address.state,
                country = address.country,
                phone_number = address.phone_number
            )

            order_status = "Confirmed"

            order_main = OrderMain.objects.create(

templates/order/admin_order_details.html
{% extends 'admindash/base_admin.html' %}
{% load static %}
{% block content %}
<section class="content-main">
    <div class="content-header">
        <div>
            <h2 class="content-title card-title">Order detail</h2>
            <h4>Order ID: {{ orders.order_id }}</h4>
        </div>
    </div>
    <div class="card">
        <header class="card-header">
            <div class="row align-items-center">
                <div class="col-lg-6 col-md-6 mb-lg-0 mb-15">
                    <span>
                        <i class="material-icons md-calendar_today"></i> <b>{{ orders.date }}</b>
                    </span> <br>
                    <small class="text-muted">Order ID: {{ orders.order_id }}</small>
                </div>
                
                <div class="col-lg-6 col-md-6 ms-auto text-md-end">
                     <form method="post" action="{% url 'admindash:order_status' orders.id %}"> 
                        {% csrf_token %}
                        <select class="form-select d-inline-block mb-lg-0 mb-15 mw-200" name="order_status">
                            {% if orders.order_status == "Canceled" %}
                            <option style="color:red;">Canceled</option>
                            {% elif orders.order_status == "delivered" %}
                            <option style="color:red;">delivered</option>
                            {% else %}
                            <option>Change status</option>
                            <option>Confirmed</option>
                            <option>delivered</option>
                            <option>Shipped</option>
                            <option>Canceled</option>
                            {% endif %}
                        </select>
                        {% if orders.order_status != "Canceled" and orders.order_status != "delivered" %}
                        <button class="btn btn-primary" type="submit">Save</button>
                        {% endif %}
                    </form>
                    {% comment %} <form method="post" action="">
                    <button class="btn btn-primary" type="submit">Save</button>
                    </form> {% endcomment %}
                </div>
                
            </div>
        </header> <!-- card-header end// -->
        <div class="card-body">
            <div class="row mb-50 mt-20 order-info-wrap">
                <div class="col-md-4">
                    <article class="icontext align-items-start">
                        <span class="icon icon-sm rounded-circle bg-primary-light">
                            <i class="text-primary material-icons md-person"></i>
                        </span>
                        <div class="text">
                            <h6 class="mb-1">Customer</h6>
                            <p class="mb-1">
                                {{ orders.address.name }} <br> {{ orders.user.email }} <br> +91 {{ orders.address.phone_number }}
                            </p>
                            <a href="#">View profile</a>
                        </div>
                    </article>
                </div> <!-- col// -->
                <div class="col-md-4">
                    <article class="icontext align-items-start">
                        <span class="icon icon-sm rounded-circle bg-primary-light">
                            <i class="text-primary material-icons md-local_shipping"></i>
                        </span>
                        <div class="text">
                            <h6 class="mb-1">Order info</h6>
                            <p class="mb-1">
                                Shipping: {{ orders.address.name }}<br> Pay method: {{ orders.payment_option }} <br> Status: {{ orders.order_status }} <br> Reason {{orders.reason}}
                            </p>
                            <a href="#">Download info</a>
                        </div>
                    </article>
                </div> <!-- col// -->
                <div class="col-md-4">
                    <article class="icontext align-items-start">
                        <span class="icon icon-sm rounded-circle bg-primary-light">
                            <i class="text-primary material-icons md-place"></i>
                        </span>
                        <div class="text">
                            <h6 class="mb-1">Deliver to</h6>
                            <p class="mb-1">
                                Address : {{ orders.address.country }}, {{ orders.address.state }} <br>{{ orders.address.district }}, {{ orders.address.street_name }}<br>{{ orders.address.house_name }}<br>PIN: {{ orders.address.pin_number}}
                            </p>
                            <a href="#">View profile</a>
                        </div>
                    </article>
                </div> <!-- col// -->
            </div> <!-- row // -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th width="10%">Product</th>
                                    <th width="10%">Name</th>
                                    <th width="10%">Unit Price</th>
                                    <th width="10%">Quantity</th>
                                    {% comment %} <th width="10%">Status</th> {% endcomment %}
                                    <th width="10%">Total</th>
                                    <th width="10%">Discount Amount</th>
                                    <th width="10%" class="text-end">Final Total</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in order_sub %}
                                <tr>
                                    <td class="align-middle">
                                        <a class="itemside" href="#">
                                            {% if item.variant.product.thumbnail %}
                                            <div class="left" style="width:100px; height:100px;">
                                                <img src="{{ item.variant.product.thumbnail.url }}" class="img-thumbnail" alt="{{ item.variant.product.product_name }}" style="width: 100%; height: auto;">
                                            </div>
                                            {% endif %}
                                        </a>
                                    </td>
                                    <td class="align-middle">{{ item.variant.product.product_name }}</td>
                                    <td class="align-middle">₹{{ item.price }}</td>
                                    <td class="align-middle">{{ item.quantity }}</td>
                                    {% comment %} <td class="align-middle">{% if item.status %}{{ item.status }}{% else %}Order Placed{% endif %}</td> {% endcomment %}
                                    <td class="align-middle">₹{{ item.total_cost }}</td>
                                    <td class="align-middle">₹{{ item.main_order.discount_amount }}</td>
                                    <td class="align-middle text-end">₹{{ item.main_order.total_amount }}</td>
                                </tr>
                                {% endfor %}
                                <tr>
                                    <td colspan="8">
                                        <div class="float-end text-end">
                                            <dl class="dlist">
                                                <dt>Subtotal:</dt>
                                                <dd>₹{{ orders.total_amount }}</dd>
                                            </dl>
                                            <dl class="dlist">
                                                <dt>Discount Amount:</dt>
                                                <dd>₹{{ orders.discount_amount }}</dd>
                                            </dl>
                                            
                                            <dl class="dlist">
                                                <dt>Grand total:</dt>
                                                <dd><b class="h5">{{ orders.final_amount }}</b></dd>
                                            </dl>
                                            <dl class="dlist">
                                                <dt class="text-muted">Status:</dt>
                                                <dd>
                                                    <span class="badge rounded-pill alert-success text-success">{{ orders.payment_status }}</span>
                                                </dd>
                                            </dl>
                                        </div>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        <div >
                            {% if orders.order_status != "Canceled" and orders.order_status != "Delivered" and orders.order_status != "Returned" %}
                            <form id="cancelForm_{{ orders.id }}" action="{% url 'order:admin_cancel_order' orders.id %}" method="post">
                                {% csrf_token %}
                                <div style="margin-left:700px;" class="mb-2">
                                    <!-- SweetAlert trigger button -->
                                    <button id="cancelButton_{{ orders.id }}" class="btn btn-danger" style="width:100px;" type="button" onclick="confirmCancel('{{ orders.id }}')">Cancel</button>
                                </div>
                            </form>
                        {% endif %}
                        </div>
                    </div> <!-- table-responsive// -->
                    
                </div> <!-- col// -->
                
            </div>
        </div> <!-- card-body end// -->
    </div> <!-- card end// -->
</section> <!-- content-main end// -->
<footer class="main-footer font-xs">
    <div class="row pb-30 pt-15">
        <div class="col-sm-6">
            <script>
            document.write(new Date().getFullYear())
            </script> ©, Evara - HTML Ecommerce Template .
        </div>
        <div class="col-sm-6">
            <div class="text-sm-end">
                All rights reserved
            </div>
        </div>
    </div>
</footer>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<script>
    function confirmCancel(orderId) {
        Swal.fire({
            title: 'Are you sure?',
            text: "Do you really want to cancel this order?",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#d33',
            cancelButtonColor: '#3085d6',
            confirmButtonText: 'Yes, cancel it!',
            cancelButtonText: 'No, keep it'
        }).then((result) => {
            if (result.isConfirmed) {
                // Submit the form if the user confirms
                document.getElementById('cancelForm_' + orderId).submit();
            }
        });
    }
    </script>
{% endblock %}

templates/order/order.html
{% extends 'user/base.html' %}
{% load static %}
{% block content %}
<div class="container mt-5">
    <h1 class="mb-4" style="font-weight:bold;">Order Completed</h1>
    
    <h3 class="text-success" style="font-weight:bold;">{{ formatted_future_date }}</h3>
    
    <div class="text-center mb-4">
        <div class="text-success display-1" style="font-weight:bold;">✓</div>
        <h1 style="font-weight:bold;">Your order is Completed</h1>
        <p style="font-weight:bold; padding-bottom:20px;">Thank You for your order. Sit tight we are processing your order<br>we will update you with your order in email</p>
        <button class="btn btn-dark" style="font-weight:bold;"><a href="{% url 'accounts:home' %}" style="color:white;">Continue Shopping</a></button>
        <button class="btn btn-dark" style="font-weight:bold;"><a href="{% url 'userdash:user-profile' %}" style="color:white;">View order</a></button>
    </div>
    
    <div class="mb-3">
        <p class="mb-1" style="font-weight:bold;"><strong>Order date:  </strong>{{ orders.0.date }}</p>
        <p style="font-weight:bold;"><strong>Order status:  </strong>{{ orders.0.order_status }}</p>
    </div>
    
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script> 
<!-- Bootstrap JS and dependencies -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
document.addEventListener('DOMContentLoaded', (event) => {
{% if messages %}
    const messages = [
        {% for message in messages %}
            "{{ message }}",
        {% endfor %}
    ];
    messages.forEach(message => {
        Swal.fire({
            toast: true,
            position: 'top-right',
            icon: 'success',
            title: message,
            showConfirmButton: false,
            timer: 3000
        });
    });
{% endif %}
});
</script>
{% endblock %}  
   